//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBoleta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBoleta()
        {
            this.TDetalle = new HashSet<TDetalle>();
        }
    
        public string NroBoleta { get; set; }
        public System.DateTime Fecha { get; set; }
        public string CodCliente { get; set; }
        public string CodVendedor { get; set; }
        public bool Anulado { get; set; }
    
        public virtual TCliente TCliente { get; set; }
        public virtual TVendedor TVendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDetalle> TDetalle { get; set; }
    }
}
