//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCategoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCategoria()
        {
            this.TCategoria1 = new HashSet<TCategoria>();
            this.TProducto = new HashSet<TProducto>();
        }
    
        public string CodCategoria { get; set; }
        public string Nombre { get; set; }
        public string CategoriaPadre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCategoria> TCategoria1 { get; set; }
        public virtual TCategoria TCategoria2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TProducto> TProducto { get; set; }
    }
}
